services:
  - type: web
    name: customer-map-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MONGODB_URI
        fromSecret: MONGODB_URI
      - key: GOOGLE_MAPS_API_KEY
        fromSecret: GOOGLE_MAPS_API_KEY